group=assets
nullTerminated=true

[file]
filename=assets/f16/model/f16.glb

[file]
filename=assets/f16/flightmodel/f16.xml
[file]
filename=assets/f16/flightmodel/reset00.xml
[file]
filename=assets/f16/flightmodel/F100-PW-229.xml
[file]
filename=assets/f16/flightmodel/hook.xml
[file]
filename=assets/f16/flightmodel/pushback.xml
[file]
filename=assets/f16/flightmodel/direct.xml

[file]
filename=assets/f16_no_pid/flightmodel/f16_no_pid.xml
[file]
filename=assets/f16_no_pid/flightmodel/reset00.xml
[file]
filename=assets/f16_no_pid/flightmodel/F100-PW-229.xml
[file]
filename=assets/f16_no_pid/flightmodel/hook.xml
[file]
filename=assets/f16_no_pid/flightmodel/pushback.xml
[file]
filename=assets/f16_no_pid/flightmodel/direct.xml

[file]
filename=src/shaders/floorshader.frag
[file]
filename=src/shaders/floorshader.vert

[file]
filename=src/shaders/skyshader.frag
[file]
filename=src/shaders/skyshader.vert

[file]
filename=src/shaders/shadowshader.frag
[file]
filename=src/shaders/shadowshader.vert

