group=assets

[file]
filename=assets/f16/f16.glb

[file]
filename=assets/f16/flightmodel/f16.xml
[file]
filename=assets/f16/flightmodel/reset00.xml
[file]
filename=assets/f16/flightmodel/F100-PW-229.xml
[file]
filename=assets/f16/flightmodel/hook.xml
[file]
filename=assets/f16/flightmodel/pushback.xml
[file]
filename=assets/f16/flightmodel/direct.xml
