group=assets

[file]
filename=models/f16/f16.glb

[file]
filename=data/aircraft/f16/f16.xml
[file]
filename=data/aircraft/f16/reset00.xml
[file]
filename=data/engine/F100-PW-229.xml
[file]
filename=data/aircraft/f16/Systems/hook.xml
[file]
filename=data/aircraft/f16/Systems/pushback.xml
[file]
filename=data/engine/direct.xml
